### ISSUE TITLE
unable to find an entry point named 'sqlite3_open_interop'

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#109]
This error occurs with v2.0.43-beta when trying to connect to a posetgresql database.

work around : Delete file  SQLite.Interop.dll  (from root of install directory)

current design is to use
x86\SQLite.Interop.dll 
or
x64\SQLite.Interop.dll 

That file might have been from previous installation.... perhaps the installer should delete that old file?

![image](https://cloud.githubusercontent.com/assets/4818531/21903659/f3cf9870-d8bd-11e6-9787-54695fdeb124.png)

**Comment by blounsbury** [comment]
The installer could delete all files too? But maybe that is overkill, but it would provide a clean install/update.

**Comment by tjrocha** [comment]
On the topic of deleting stuff, can we also consider having the installer delete/rename the existing tsdatabase.pdb file in the default directory? I've had users get errors on opening a new installation because PISCES opens an old file by default and the new installs might not be backwards compatible.

**Comment by blounsbury** [comment]
We've been discussing having a start screen of some sort. Where the user might be able to select from recent files, open an existing file, or create a new database. Instead of trying opening a default database.

**Comment by ktarbet** [comment]
If innosetup can delete --  lets at least delete the SQLite.Interop.dll in the root dir.
