### ISSUE TITLE
Is there a need for HDB-POET linked to Pisces

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#154]
Now that HDB-POET has Pisces embedded, can we drop HDB-POET within Pisces?

The following dependencies are required by Poet:
Devart.*
SpreadsheetGear (specific version)
TeeChart (specific version)

The web HDB Series can access all data without any third party.

**Comment by tjrocha** [comment]
Should be ok to drop the POET UI since it has too much baggage. Would it be ok if I replaced it with a Series() constructor that uses the internal web service? I'm pretty close to getting Denver to give me a proxy that would enable calls to this service. I'm also pretty close to releasing a new version of POET with the embedded Pisces so the timing would work out. Thanks!

**Comment by ktarbet** [comment]
Can HDBWebSeries read model data?   That might be all we need?

**Comment by ktarbet** [comment]
Here is the link https://github.com/usbr/Pisces/blob/master/TimeSeries/HDB/HDBWebSeries.cs

**Comment by tjrocha** [comment]
it can read model data. need optional arguments below attached to the query url.

&table=M&mrid=XXXX

**Comment by tjrocha** [comment]
we can also restructure it so it requests and parses the json output for speed.
