### ISSUE TITLE
Pisces display problems

### ISSUE THREAD

**Issue by tjrocha** [usbr/Pisces#177]
Pisces UI has problems displaying on high-resolution and/or high dpi laptops/monitors. Most noticeable on some visual elements such as mouse pointers, UI arrows, Series Tree labels, and maybe a few others.

![image](https://user-images.githubusercontent.com/8174126/51271390-abc98900-1984-11e9-9c85-a56c9cf5ebee.png)

**Comment by tjrocha** [comment]
Deleting the section below out of app.manifest fixes the issue. @ktarbet -- is this still needed?

```
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!-- A list of all Windows versions that this application is designed to work with. 
      Windows will automatically select the most compatible environment.-->

      <!-- If your application is designed to work with Windows Vista, uncomment the following supportedOS node-->
      <!--<supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"></supportedOS>-->

      <!-- If your application is designed to work with Windows 7, uncomment the following supportedOS node-->
      <!--<supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>-->

      <!-- If your application is designed to work with Windows 8, uncomment the following supportedOS node-->
      <!--<supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"></supportedOS>-->

    </application>
  </compatibility>
```

![image](https://user-images.githubusercontent.com/8174126/51272449-5d69b980-1987-11e9-83cc-23ee897cdb3f.png)

**Comment by blounsbury-usbr** [comment]
Maybe the code image is not showing what you deleted? The code shown are comments (). Maybe you deleted this section from the app.manifest?

`
<asmv3:application>
  <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
    <dpiAware>true</dpiAware>
  </asmv3:windowsSettings>
</asmv3:application>`

This section sets Pisces as DPI aware, which seems to be working from your first screenshot (fonts are larger and clear). However, it looks like the treeview (Aga.Controls.dll) is not DPI aware. Your second screenshot shows non-DPI awareness where you can see that fonts are the same size and fuzzy.

Pisces is using AutoScaleMode:Font on the forms. I don't know if the other options make things better or not. Note to developers, when designing forms or editing forms your monitor should be set to 96 DPI, otherwise the form will not scale to other resolutions properly. Maybe this has impacted the view on some forms?

Is there a native winforms tree control we could use? Also, not sure about mouse pointer differences...

**Comment by tjrocha** [comment]
Your commit fixed my issue. Thanks! We might look into moving the framework to .Net 4.7 since there are some enhancements that we could probably use to fix the other scaling issues. Switching this issue from a bug to an enhancement for consideration. 

https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms

**Comment by blounsbury-usbr** [comment]
It looks like .Net 4.7.2 was provided to Windows 10 in an April 2018 update so no issue there. I'm not aware of anything else that would cause an issue if we moved framework.
