### ISSUE TITLE
Fix IDWR Data Import

### ISSUE THREAD

**Issue by tjrocha** [usbr/Pisces#184]
IDWR data import via Data>Add>From Web>IDWR Series doesn't work when it comes time to fetch the time-series data. Fetching the metadata for the drop-downs still work but fetching time-series data doesn't. Possible change to the API end point and/or inputs? 

Research materials:
https://research.idwr.idaho.gov/apps/Shared/WaterServices/
https://research.idwr.idaho.gov/apps/Hydrologic/Accounting/
https://idwr.idaho.gov/files/help/Accounting-Time-Series-Users-Manual.pdf

**Comment by ktarbet** [comment]
If you look at the history is says: ability to get historical or model data from idwr, not yet in UI @blounsbury-usbr

**Comment by tjrocha** [comment]
Reopened issue to continue work on:
- allowing the download of other parameters (natural flow, stored flow, reach gains, etc) from IDWR's Accounting (ALC DB) -- IdwrApiResponse.cs needs to be reworked for this...
- Right-Click-Update functionality so users can request data using the Series.ConnectionString property

![Capture](https://user-images.githubusercontent.com/8174126/70463283-d9765f80-1a79-11ea-85d6-6a09629510ca.PNG)

**Comment by blounsbury-usbr** [comment]
Sorry, got wrapped up in a modeling project. My memory is hazy. I know we were trying to get Accounting data into Pisces and I'm pretty sure we did, but then it was abandoned due to DB inaccuracies. Though I don't see how my hack in the code would have made that work even temporarily in the UI. Maybe I clicked incorrectly in visual studio and committed. I would note that IdwrApiResponse.cs has already been reworked to some extent as has IDWRDailySeries.cs. We don't currently have any need for accounting data from IDWR so I would put this enhancement on the back-burner or we could revert the edits and delete this request until there is a need.

**Comment by tjrocha** [comment]
Working implementation pushed. Need to modify import UI so it can handle different IDWR Accounting Site Types. JSON response has different property labels that we would need to handle in the UI and on Pisces/Reclamation.TimeSeries/IDWR/IdwrApiResponse.cs

Sample Site Type-D: https://research.idwr.idaho.gov/apps/Shared/WaterServices/Accounting/model?siteid=13085500&yearlist=2016,2015&yeartype=CY&f=json

Sample Site-Type-F: https://research.idwr.idaho.gov/apps/Shared/WaterServices/Accounting/model?siteid=13088000&yearlist=2016,2015&yeartype=CY&f=json

**Comment by tjrocha** [comment]
Should have clarified earlier on that this work was re-requested by the USFO so they can do their work of tracking water accounting for the basin.

Recompiled installer for USFO testing. Waiting on feedback.

**Comment by jdalling** [comment]
@ktarbet @blounsbury  @tjrocha  - Hello rock-stars of decision support tools, I hope you are all doing well and I just wanted to give you all a shout out for the great work that you do. 

Regarding this IDWR data import fix request, this stems from an inquiry by the USFO Water Management Group about the accounting data not updating in Pisces. For background, our group uses this data in a multitude of ways including applications to real-time operations on the daily time-step, this includes usage to calculate reach gains, storage balances, consumptive use estimates, natural flow projections, historical trends, analogs years, etc. Additionally, we use accounting data in stakeholder presentations, public information meetings, news/media outreach, and in managerial briefings, among other uses. I can only speak for myself, but it would be really neat if the data would update like it does for the other external agency data.

For context, it is not a major to lift to pull the data repeatedly in separate pisces queries to get the most recent data, and transferring data to excel and reading back into Pisces is workable, but it would  be really neat if the update function worked for the IDWR data which would allow me to do most of the real-time operation and broad spectrum water management work primarily in one platform (pisces). Hopefully I am explaining the issue and benefits well enough. In short and in my opinion, this would be a very helpful fix. I feel like I ask Rocha for help on these things quite often but recognize that he has other duties. No pressure on it, just wanted to make sure that the issue was expounded upon a little bit more. Please feel free to ask me any questions, including anything about need, and I would be happy to expound further.  

I would like to help as much as I can but I recognize your expertise exceeds mine substantially. 

The image below portrays an example of multiple queries for the same accounting data approximately a week apart. This image  portrays the current process to get the most most recent accounting data in Pisces. From what I can tell, the issue in Pisces appears to be with the update data function because the initial query for data from IDWR works fine - Thank you very much for your time and consideration
![QueryofTotalNaturalFlowaboveMilner](https://user-images.githubusercontent.com/51172335/168441863-21ffea29-15b8-48ea-9bbf-f23e6c5f6c95.jpg)

**Comment by blounsbury-usbr** [comment]
@jdalling I think I have this fixed with pull request #203. There may be some other work to do, as the current setup doesn't allow pulling NATQ for 13088000.
