### ISSUE TITLE
i think Pisces need self store engine.

### ISSUE THREAD

**Issue by sgf** [usbr/Pisces#212]
i think Pisces need self store engine.
rdbms are not good at to do that.

**Comment by ktarbet** [comment]
@sgf Thanks for creating an issue.   

Would you please explain what you mean by 'self store engine' ?   

The closest we have to NoSQL type data is using blobs to store ensembles of time-series 
 - for example: https://github.com/usbr/Pisces/blob/master/TimeSeries/EnsembleSeries.cs

**Comment by sgf** [comment]
> @sgf Thanks for creating an issue.
> 
> Would you please explain what you mean by 'self store engine' ?
> 
> The closest we have to NoSQL type data is using blobs to store ensembles of time-series
> 
> * for example: https://github.com/usbr/Pisces/blob/master/TimeSeries/EnsembleSeries.cs

like influxdb

**Comment by blounsbury-usbr** [comment]
@sgf The other question would be, why? Why do you think Pisces needs something like influxdb rather than rdbms? Is there some computation or operation within Pisces that you've found to be rather slow, and you think influxdb would improve the operation? Or what is your reasoning?

**Comment by sgf** [comment]
> @sgf The other question would be, why? Why do you think Pisces needs something like influxdb rather than rdbms? Is there some computation or operation within Pisces that you've found to be rather slow, and you think influxdb would improve the operation? Or what is your reasoning?

1. I don't think it can be called a database without a self-storage engine
2. RDBMS is not optimized for storing time series data, including compression, indexing, write performance and other aspects.

I don't actually know much about influxdb, but I know it's the best out there.
However, as a C# developer, I'd love to see a similar open source project for C# so that I don't need to make cross-language calls.

**Comment by blounsbury-usbr** [comment]
I don't think Karl or I understand what you mean by a 'self-storage engine' and neither does Google. Pisces currently stores data in an SQLite database (the *.pdb file that Pisces creates), how that can not be called a database without a 'self-storage engine' I do not understand. All data, including timeseries data is stored in that SQLite database file.

Agreed. A NoSQL or TSDB may be faster, as stated by influxdb: https://www.influxdata.com/the-best-way-to-store-collect-analyze-time-series-data/

"Time series databases are proven to outperform relational databases for time series data to make your data work faster for you."

But this does not mean that a relational database is not perfectly suited to the Pisces application or any other time series database application (it's been done for many many years). Pisces is a simple per-user desktop application. It is not a database server where thousands of time series operations will be called against the database constantly.

If there is some computational operation within Pisces that you have noticed to be rather slow, let us know and we could look into it. Or feel free to look into the operation yourself since you are a C# developer.

In the meantime, switching Pisces to a TSDB, we do not currently have time or funding to accomplish. Pisces is open source so feel free to make the modification to a NoSQL or TSDB database structure and submit a pull request. We'd be happy to take a look and see how performance is improved! Thanks.

**Comment by sgf** [comment]
> I don't think Karl or I understand what you mean by a 'self-storage engine' and neither does Google. Pisces currently stores data in an SQLite database (the *.pdb file that Pisces creates), how that can not be called a database without a 'self-storage engine' I do not understand. All data, including timeseries data is stored in that SQLite database file.

It has its own designed data storage file format, design its own file structure, and design its own API for reading and writing the file structure data.
(There are InnoDB, MyISAM, etc. storage engines in MySql).

**Comment by sgf** [comment]
In any case, your works is still commendable.
