### ISSUE TITLE
64 bit version of Pisces needed.

### ISSUE THREAD

**Issue by ktarbet** [usbr/Pisces#40]
We may need some extra configuration for Sqlite to support 64 bit -- The Nuget package has ability for both 32/64 bit.  It might just work?   I think the other code would be ok 64 bit.

**Comment by tjrocha** [comment]
Working test 64BIT branch created with 7c08be546ee2282d6b10efa358d646ff725abae1. Had to recompile Aga.Controls from source to 64bit .Net40 and reinstall SQLite from NuGet.

**Comment by tjrocha** [comment]
Windows Appveyor tests fail on build due to the common error below. It seems that the build is trying to load 32bit versions of SQLite?

[00:02:18]    System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
[00:02:18]    at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
[00:02:18]    at System.Data.SQLite.SQLite3.StaticIsInitialized()
[00:02:18]    at System.Data.SQLite.SQLiteLog.Initialize()
[00:02:18]    at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
[00:02:18]    at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
[00:02:18]    at Reclamation.Core.SQLiteServer.Table(String tableName, String sql, Boolean AcceptChangesDuringFill) in C:\projects\pisces\Core\SQLiteServer.cs:line 439
[00:02:18]    at Reclamation.Core.SQLiteServer.Table(String tableName, String sql) in C:\projects\pisces\Core\SQLiteServer.cs:line 425
[00:02:18]    at Reclamation.Core.SQLiteServer.TableExists(String tableName) in C:\projects\pisces\Core\SQLiteServer.cs:line 315
[00:02:18]    at Reclamation.TimeSeries.TimeSeriesDatabase.InitDatabaseSettings(BasicDBServer server) in C:\projects\pisces\T
[00:02:18] imeSeries\TimeSeriesDatabase.cs:line 197
[00:02:18]    at Reclamation.TimeSeries.TimeSeriesDatabase..ctor(BasicDBServer server, LookupOption lookup, Boolean readOnly) in C:\projects\pisces\TimeSeries\TimeSeriesDatabase.cs:line 162

**Comment by ktarbet** [comment]
Are you trying to  detect if 32 bit or 64 bit at runtime?  We should have a single version that is any architecture. However,  there might be [MODSIM](http://modsim.engr.colostate.edu/) changes required as well.

from: https://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki 
"If the development and customer machines may have different processor architectures, more than one binary package may be required. For this situation, using the native library pre-loading feature is highly recommended. It is available as of version 1.0.80.0 and enabled by default. In order to take advantage of this feature, the separate managed and interop assemblies must be used with XCOPY deployment (i.e. this feature is not supported by the mixed-mode assembly, nor when the assembly is deployed to the global assembly cache), resulting in an application deployment that looks something like this:
 	
<bin>\App.exe (optional, managed-only application executable assembly)
<bin>\App.dll (optional, managed-only application library assembly)
<bin>\System.Data.SQLite.dll (required, managed-only core assembly)
<bin>\System.Data.SQLite.Linq.dll (optional, managed-only LINQ assembly)
<bin>\System.Data.SQLite.EF6.dll (optional, managed-only EF6 assembly)
<bin>\x86\SQLite.Interop.dll (required, x86 native interop assembly)
<bin>\x64\SQLite.Interop.dll (required, x64 native interop assembly)"

**Comment by ktarbet** [comment]
In the 64bit branch I see some entity framework references (EF).  We can drop these to simplify -- EF is not being used.  

Here is  link about supporting both 32 and 64.  http://stackoverflow.com/questions/7264383/options-for-using-system-data-sqlite-in-a-32bit-and-64bit-c-sharp-world.   This example seems to use some code.

**Comment by ktarbet** [comment]
Core.dll and TimeSeries.dll are now Platform Target: Any CPU

Pisces reference Aga.Controls is x86 only at this point, that needs to be re-compiled.

**Comment by blounsbury** [comment]
Aga.Controls re-compiled to Any CPU.

**Comment by blounsbury** [comment]
I think the biggest obstacle to this goal is likely the Microsoft Access Database Engine which allows Pisces to read Microsoft Access files. Microsoft does not currently support the side-by-side installation of 32- and 64-bit Access Database Engine. So, if Pisces is Any CPU and the machine platform is 64-bit it will be looking for the 64-bit Access Database Engine, but if the user either hasn't installed it or if they have 32-bit Office installed and therefore the 32-bit Access Database Engine it will fail.

In MODSIM I setup the installer to warn people if a platform vs access database engine mismatch was detected and provided instructions on how they could try to work around it but it can be messy:
https://bitbucket.org/engr_csu/csu_geodss/wiki/Home

![image](https://cloud.githubusercontent.com/assets/1508213/24763527/dbdf9dae-1aae-11e7-83c7-93ab1e9a6c8a.png)

One solution would be to remove support for Microsoft Access Database files and force MODSIM users to use version 7 output format and modify Pisces to read version 7 MODSIM output. But I think some people may read other Access files than just MODSIM output.

Is there any other way to read Access Databases? I'm struggling to find anything.

**Comment by ktarbet** [comment]
Longer term is would be best to modify MODSIM to use SQLite :)

**Comment by blounsbury** [comment]
Agreed. Don't others use Access import functionality. I think the Corps sent their model output in an Access database that Pisces was able to load? Access support may be more than MODSIM?

**Comment by ktarbet** [comment]
Yes, good point - "BPA hydsim"  uses Access.

**Comment by blounsbury** [comment]
Hmmm ... Difficult dilemma. The instructions on MODSIM's wiki to use 64-bit MODSIM with 32-bit Office worked when I tried it but would likely require administrator privileges and it's messy for the average user. But it should allow Any CPU Pisces to work ... I think.

**Comment by blounsbury-usbr** [comment]
closed via 0bb46e7def3f7b66aa5efd212d4ad370a9c18de8 and e4306dad40b68bb0093adc370121f55b7799aa11, although Pisces would still require a users machine architecture to match microsoft office/access (i.e., 64 bit and 64 bit, or 32 bit and 32 bit)
